_projects/it/cie.md
Il termine "Certificato SSL" è improprio. Userei "Certificato digitale" che ha una bella descrizione su Wikipedia oppure "Certificato X509 per operazioni digitali/online" che è tecnicamente più corretto.
=> Use "certificato digitale" instead of "certificate SSL"

_projects/it/anpr.md
It'll take us a few more days to fix the layout of sphinx tables.
Point to the tables that work in the mean time.
This also brings consistency between what the github archive and developers.italia.it point to.
=> Change the link to the error tables

Gemfile
La versione 0.9.2 di jekyll fissa un bug che consiste
nell'assenza di spazi tra il localname del tag entry e
l'attributo lang dello stesso (fixes #30)
=> Upgrade a jekyll 0.9.2

Gemfile, _config.yml, _includes/card.html, _includes/head.html, _includes/pills.html, _layouts/post.html, _layouts/posts_by_tag.html, _plugins/ext.rb, _posts/it/2017-02-24-lancio.md, _posts/it/2017-05-25-pubblicata-roadmap-spid.md, _posts/it/2017-06-01-vuoi-lavorare-developers-italia.md, _posts/it/2017-07-27-hack-developers-hackathon-per-pubblica-amministrazione.md, _posts/it/2017-09-07-hack-developers-meetup.md, _sass/_developer.scss, news/index.html
Attenzione, il plugin jekyll-tagging si aspetta nel frontmatter "tags" piuttosto che "categories" come attualmente utilizzato. Dobbiamo quindi decidere se eliminare "categories" in favore dello standard tags oppure fare override del plugin.
Al momento nel FM dei posts ci sono sia categories sia tags, con valori uguali.
@rasky
=> Added a new plugin (jekyll-tagging) to obtain post-lists per tag

_config.yml, _includes/header.html
Typo fix for the name of  the Digital Team. Now "full" on the footer and always "short" on the slimheader
=> Footer typofix

Gemfile, Gemfile.lock
This commit upgrades our website to jekyll 3.6.0. Full changelog at https://jekyllrb.com/docs/history/
I've also upgraded our ruby stack to 2.4.2 - no problems reported.
=> Upgrade to jekyll 3.6.0 and ruby 2.4.2

_projects/it/18app.md
I link nella versione originale erano errati.
Rimosso il primo link che puntava alla versione di prova, ormai obsoleta. L'unica guida rilevante al momento è quella per gli esercenti.
=> fix: Corretti link guida 18app

_posts/it/2018-03-12-code-hands-on-laboratori-aperti-per-la-milano-digital-week.md
Nel post `Code hands-on: laboratori aperti con Developers Italia per la Milano Digital Week` c'è un `:` nel titolo che non piace a Jekyll
=> Fix post digital week

_posts/it/2018-04-16-linee-guida-su-acquisizione-e-riuso-del-software.md
Crea news per l'apertura della consultazione sulle "Linee guida sull’acquisizione e il riuso del software" fino al 5 maggio 2018
=> Crea news su consultazione per lg software

_data/tools.yml
Using SVG icons also for tools in the English version of the website.
=> Switch en tools icons to SVG

_layouts/home.html, _posts/en/2018-05-23-un-ambiente-di-test-aperto-a-tutti-per-anpr.md, _posts/en/2019-03-06-developers-italia-al-google-summer-of-code-2019.md, _posts/it/2017-02-24-lancio.md, _posts/it/2017-05-25-pubblicata-roadmap-spid.md, _posts/it/2017-06-01-vuoi-lavorare-developers-italia.md, _posts/it/2017-07-27-hack-developers-hackathon-per-pubblica-amministrazione.md, _posts/it/2017-09-07-hack-developers-meetup.md, _posts/it/2017-10-03-hack-developers-ti-aspettiamo.md, _posts/it/2017-10-11-hack-developers-come-e-andata.md, _posts/it/2017-10-23-hack-developers-ecco-i-vincitori-fast-rabbit.md, _posts/it/2017-11-08-hack-developers-tutti-i-progetti-vincitori-del-code-sprint.md, _posts/it/2018-02-21-developers-italia-al-google-summer-or-code.md, _posts/it/2018-03-07-ti-presentiamo-il-nuovo-docs-italia.md, _posts/it/2018-03-12-code-hands-on-laboratori-aperti-per-la-milano-digital-week.md, _posts/it/2018-04-05-linee-guida-in-consultazione.md, _posts/it/2018-04-16-linee-guida-su-acquisizione-e-riuso-del-software.md, _posts/it/2018-05-16-un-webinar-per-le-software-house-sull-acquisizione-e-il-riuso-del-software.md, _posts/it/2018-05-23-un-ambiente-di-test-aperto-a-tutti-per-anpr.md, _posts/it/2019-03-06-developers-italia-al-google-summer-of-code-2019.md, en/news/index.html, it/news/index.html
Front news in home page it currently displayed in a random language because no filter is applied.
This PR fixes the issue. I changed the `locale` values from `it_IT` to `it` because it is allowed by the jekyll-paginate-v2 plugin, so that we can match that field against the `active_lang` variable.
=> Bugfix: news in home page were not filtered by active language

_data/apis.yml, circle.yml
Restores proper functioning of circleci in test
@libremente  NB: needs `squash`
=> Fix circleci test build

_layouts/api.html
As of now, the API listing page has broken links to pages which are tagged as "coming soon". 
Those links are safely removed by this PR.
Fixes #355.
@sebbalex
=> Fix coming soon API listing. 

_data/apis.yml
Since there is no fix available yet, I propose switching the [API page](https://developers.italia.it/it/api/daf-ckan) to coming soon in order not to display an error in the page. 
If not, do you have an idea about what's needed to fix it? @ioggstream @jenkin 
See https://github.com/italia/developers.italia.it/issues/359 for further details.
=> Switch DAF API to coming soon

_config.yml
This PR switches the logo from the previous PNG one to the SVG icon. 
Fix #339 .
The new logo is slightly bigger but I think it's OK. 
@sebbalex
=> Switch logo to SVG.

_layouts/software-details.html
This PR checks whether a contact's email exist or not before actually templating the `mailto` address. Trivial solution for #379.
=> Add check on contact email

_plugins/data_page_generator.rb
With this PR, we can configure distinct data keys to use for page title and page name (filename). In case of public administrations, we want to use the iPA code as filename and their full name as page title:
```yaml
- index_files: false
name: ipa
title: entityName
data: crawler.amministrazioni
template: brand-pa
defaults:
lang: it
dir: it/pa
```
=> Allow to configure the data key to use for page title

_data/apis.yml, swagger/components/Hero.js
This PR:
- adds an import of `projects.js` in order to correctly render the DAF API page. In such a way, the project is correctly located and processed and the react error is avoided. 
See #359 for further details. 
@ioggstream
=> Add missing import for daf swagger ui

_layouts/software-details.html
- Remove href when `contractors.website` is not defined
- Add external link icon when `contractors.website` is defined
- Add email icon when `contact.email` is defined
See https://github.com/italia/developers.italia.it/issues/330.
Please note that I wasn't able to reproduce the situation where `website` key is missing from a contractors. I'm pretty sure the fix should work fine but please double check. (or tell me how can I do the check). Thanks
=> Issue #330: remove href when url is missing

_data/l10n.yml
The website references listed screenshots as "photos". I think it sounds very weird, especially in Italian: a software has no "photos".
While "screenshot" is probably too technical, I feel "images" is a good compromise, hence I propose this change.
=> Fix the wording: photos->images

Makefile, circle.yml
As of #406 data are served statically to enhance CI
=> Data produced by crawler are statically served #406

assets/scripts/esDevelopersItaliaQuery.js
When browsing search results in a language which was not present in `description` section of a valid `publiccode.yml` browser threw an error due to an undefined description object.
=> Fix search engine when description is not present in language set

_layouts/home.html, _layouts/platform.html, _pages/en/contacts.md, _pages/it/contatti.md, _platforms/en/anpr.md, _platforms/it/anpr.md
This PR removes the newsletters temporarily. 
As such:
* Disables the newsletter form in homepage.
* Removes the newsletter form from the `platform.html` layout.
* Removes the newsletter form from the contacts pages. 
@sebbalex
=> Remove newsletter forms

_pages/en/search.md, _pages/it/search.md, _sass/search-page.scss, _sass/softwares.scss, assets/scripts/esDevelopersItaliaQuery.js
This PR will:
- fixes #370
- fix typo in scss
- results and sortBy filter are now aligned horizontally in search page
and aims to discuss if text "Catalogo" is a good for replacement "Hai Cercato" in search page when no keyword is specified.
=> Fixes #370 - text replacement for no keyword in search

assets/scripts/esDevelopersItaliaQuery.js
- total results update after search did not be triggered in mobile views
- page params will be reset anytime `type` filter has state changes #446 
- moved some logic in a separate function
=> Fixes #446

_config.yml, _layouts/api-details.html
Fixes #256 
APIs pages were set by default to lang `it` even if they were published under another language folder, this caused duplicated entries in search engine when website is set to ITA lang and no results with ENG lang.
Search engine will filter results based on language set in website so they should be visibile in both languages even if they are published in only one of them.
=> Fix #256 - APIs page indexed twice

_data/menu_items.yml
This PR:
* removes the GSoC entry from the menu;
Do you think we should remove also the pages? @sebbalex 
Maybe they could stay there without a menu link for future reference.
=> Remove GSoC

_platforms/en/cie.md, _platforms/it/cie.md
This PR adds the cieid-android-sdk repository to the CIE page.
=> Add cieid-android-sdk to the CIE page

.gitignore, _layouts/internal-long.html, _pages/en/reuse/acquisition.md, _pages/en/reuse/publication.md, _pages/it/info-privacy-communitycall.md, _pages/it/privacy-policy-18app.md, _pages/it/riuso/acquisizione.md, _pages/it/riuso/pubblicazione.md
This PR:
* Adds the title in the `internal-long` layout
* Adds div that makes content in the `internal-long` layout inherit the `Lora` font and not the generic `Titillium web` reserved for the text outside layouts. 
* Also adds some top and bottom padding to the page.content
* Fixes #554
* Also Fixes #508
=> [#554] Add title to internal-long layout

CODE_OF_CONDUCT.md
This PR:
* adds a Code of Conduct respecting the DTT's guidelines. See [here](https://github.com/teamdigitale/licenses/blob/master/CODE_OF_CONDUCT.md)
As such, it:
* Fixes #567
=> [#567] Add Code Of Conduct

Gemfile, Gemfile.lock, Makefile
This PR:
- defining the path in the configuration instead of as a parameter in the install command (deprecated)
-  setting gem tzinfo-data for all systems instead for only the win systems
=> [#532] Fix deprecation warnings on build

_includes/sw-pair-blocks.html
Make the buttons and title be aligned across cards in
the /software page.
Fix #581.
After the patch:
=> Fix button alignment in /software page.

.gitignore, Makefile, _layouts/github-issues.html, assets/vendor/bootstrap-italia, assets/vendor/chart.js, assets/vendor/jquery
Linking the assets is simpler and it doesn't require the container
to have write permissions on assets/vendor.
=> Link the assets needed at fs level.

Dockerfile, Makefile
Remove the obsolete deploy-vm Makefile target since the site is now
deployed using GitHub Pages.
=> Remove deploy-vm target and its rsync dependecy.

.env.example, Dockerfile, README.md, docker-compose.yml
Support the RUNAS variable to run as the specified user.
The docker container is used only during development, ie. with the work
directory always bind mounted to a directory on the developer's box.
This means we want the container to always run as the current user and
RUNAS to be mandatory.
Fix #596.
=> Run the container as the specified user.

Gemfile.lock
Kramdown-parser was added only to Gemfile and not to the .lock one.
@sebbalex
=> Add kramdown-parser to Gemfile.lock

.env.example, Dockerfile, README.md
Set the variable to the reasonable value. The developer doesn't have
to care about Nokogiri's minutiae.
=> Hardcode NOKOGIRI_USE_SYSTEM_LIBRARIES to true.

.env.example, README.md
Document the environment variables right where they're used, in the
.env file.
=> Document the environment variables in place.

.circleci/config.yml, Dockerfile, Makefile
When in test or production, bundle install must error out if
Gemfile.lock doesn't exist or doesn't match with it the Gemfile.
Pin the bundler version as well.
=> Use bundle install --deployment in test and production.

_data/l10n.yml, _includes/set-tag.html, _layouts/software-details.html, assets/scripts/esDevelopersItaliaQuery.js, assets/scripts/esQuery.config.js
As already mentioned in #287, this PR tackles:
* Audience scope are displayed in software detail and it is allowed to browse the catalog filtering by them
- Fixes #287
=> Add audience scope in software

Gemfile, Gemfile.lock, _config.yml, _includes/home-listing-sw.html, _layouts/brand-pa.html
As mentioned in #369, the sw ordering should change.
As such, this PR changes the following:
-  ~Software page: it should be ordered randomly~
Fix:
* Fixes #369
=> [#369] Change sw display ordering

.env.example, assets/js/esQuery.config.js, webpack.common.js
Use the ELASTICSEARCH_FRONTEND_URL if set to get the frontend
Elasticsearch URL instead of just hardcoding it.
Fix #625.
=> Add ELASTICSEARCH_FRONTEND_URL environment variable.

assets/js/esDevelopersItaliaQuery.js
As already mentioned in #679 , this PR tackles:
* Administration category in search page was statically set to "administration", now it is localized and themed like others.
- Fixes #679
=> administration category in search page was statically linked

Gemfile, Gemfile.lock, assets/js/github-issues.js, scripts/github_importer.rb
* Support multiple organizations
* Get all issues labeled with EITHER 'help wanted' or 'Hacktoberfest',
not just 'help wanted'.
* Remove parallelism cause GitHub explicitly says not to use it.
Fix #662.
=> Refactor github_importer.rb and show teamdigitale in /en/to-do.

.env.example
Properly document GITHUB_ACCESS_TOKEN in .env.example and
remove JEKYLL_NO_GITHUB since it's no longer used.
=> Properly document GITHUB_ACCESS_TOKEN and remove JEKYLL_NO_GITHUB.

.env.example, Dockerfile, docker-compose.yml
Use our custom Elasticsearch image with preloaded data in the
development environment.
=> Use italia/publiccode-tools-elasticsearch.

_layouts/internal-simple.html, assets/scss/main.scss
As already mentioned in # 699, this PR corrects the display of the images present at the beginning of the "Simplelayout".
Such as?
Added a `div` that contains a background image, i.e. the header image. This `div` has replaced the `img` tag previously present and has a minimum height of 405px and is responsive on width.
**Before:** ![image_before_1](https://user-images.githubusercontent.com/7593569/94287956-31257f00-ff57-11ea-9354-012077e2bd1f.PNG)
**After:** 
- [ x ] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [ x ] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ x ] Have you written new tests for your core changes, as applicable?
- [ x ] Have you successfully ran tests with your changes locally?
- [ x ] …
=> [#699] Updated heading background images on .simplelayout

_includes/share.html, assets/scss/main.scss
As already mentioned in #723 , this PR tackles:
* Renders the correct icon.
* There was unequal padding, which made the icon wrapper shape irregular. Changed it the correct value.
The icons render like following now:
- Fixes #723
=> [#723] Icon wrapper rendering fix

_layouts/posts_by_tag.html
This PR fixes the `close` icon in the news category filter and it also centers the category name.
Before:
After:
- Fixes #730
=> [#730] Fixed news category close icon and centered category text

_includes/community-leaders.html, _includes/community.html, _includes/github_team_members.html
Use the resizing parameter of github urls instead of getting big images and resizing them after.
As already mentioned in #692 this PR tackles:
* Using the parameter `s=` of Github's avatar url to resize the image
- Fixes #692
=> [#692] Use github resizing url for avatars

_includes/github_team_members.html
The github member navigation in the sections within "Platforms" now works correctly.
The problem was that the variable `indicators` always arrived as 0 when the team members were 6 or more, and it did not correctly perform the comparison to add more navigation circles in the carrousel, since it began to count from 1 in the following way `{1...indicators}`.
One more module was assigned when the number of team members is greater than 5.
- Fixes #688
=> #688 [ Fixed ] "Community leaders" Does not have "Dot" Pagination

_includes/display-logo.html, assets/js/search.handlebars
=> Properly size logos in thumbnails.

_includes/footer--simple.html
Fixed the margin for the social links and adjusted the rest of the content on desktop view
As already mentioned in #735, this PR tackles:
1. The social links in the footer had no margin
I've added some padding for the social links as well as the normal links (below the social).
I've also changed the content spacing in desktop view since they were too close together.
- Fixes #735
=> Update social link margin fixed

_layouts/api-details.html
As suggested by @bfabio https://github.com/italia/developers.italia.it/issues/678#issuecomment-704068256, the PR makes the detail page of comingsoon APIs display API info and comingsoon badge instead of the error message "No API definition provided".
Result:
- Fixes #678
=> [#678] Detail page of comingsoon APIs shows API info

_includes/github_team_members.html
As already mentioned in #708], this PR tackles:
Adds the alt attribute to the img tag put the team member name as text
- Fixes #708
=> [#708] Adds the alt attribute to the img tag to solve the a11y warning

assets/scss/main.scss
This fixes the issue https://github.com/italia/developers.italia.it/issues/734 with the incorrect margin in mobile view.
I have added a 10px margin-bottom to fix it.
As already mentioned in #734 , this PR tackles:
The added margin between the categories cloud. I added a bottom margin to main.scss
- [X ] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [] Ready for review! :rocket:
- Fixes #734
=> added margin-bottom to .Pills .Pill in main.scss

assets/js/esDevelopersItaliaQuery.js
Fix alphabetical order breaking the search. This works just for
Italian for now.
Fix #650.
See also italia/developers-italia-backend#201
=> Fix alphabetical order breaking the search.

scripts/github_importer.rb
Hacktoberfest 2020 is over, don't export issues labelled with
"Hacktoberfest". As a consequence, the UI won't show them anymore.
=> fix: don't export Hacktoberfest issues

_includes/footer--simple.html, _includes/head.html
As already mentioned in #808 , this PR tackles:
* move GA snippet to the end of head tag.
- Fixes #808
=> fix: move google analytics snippet from body to head

assets/scss/main.scss
As already mentioned in #768 this PR tackles:
* Horizontal viewport overflow for mobile screens, exactly `xs` (<576px) screens.
- Fixes #768
=> [#768] Fix horizontal overflow

_config.yml, assets/images/icon-type-unknown.svg, assets/js/esDevelopersItaliaQuery.js, assets/scss/main.scss
Don't index PAs pages to Elasticsearch because they are already
included as 'administrations'.
Also rename 'misc' search result hits to a more user friendly 'page'.
Fix #664, fix #672.
=> fix: don't index PAs to Elasticsearch

vercel.json
Set the site name and instruct Vercel to serve HTML with
their extension removed (to mimic Jekyll serve and GitHub pages).
=> chore: add Vercel configuration file

_platforms/en/spid.md, _platforms/it/spid.md
italia/spid-passport was obsolete and is archived now; link
to the new library for Express.js.
=> chore: change spid-passport to spid-express

.vercel/ignore-gh-pages.sh
Looks like Vercel "Ignored Build Step" doesn't support piping (yet?),
so we're forced to use an external script ("bash .vercel/ignore-gh-pages.sh").
=> chore: tell Vercel not to build the gh-pages branch

assets/scss/main.scss
Changed sideblock to sticky
As already mentioned in #,687 this PR tackles:
* Keeps sideblock always in viewport 
In particular,
* Changed position to `sticky` at a top value of `100px`. This will keep the sideblock always at a fixed distance of 100px from top of the window instead of letting it scroll up of the view.
- Fixes #687
=> [#687] Sticky sideblock for app page

.github/workflows/danger-js.yml
Use developers-italia-bot token for Dangerjs comments on an
issue.
The automatic GITHUB_TOKEN from GitHub Actions is not available
to PRs from external repos.
Fix #818.
=> chore(ci): use developers-italia-bot for Dangerjs

.circleci/config.yml, Makefile, package.json, scripts/pa11y.sh
Speed up Pa11y by running only once for pages in /pa, software
or /api.
If one page passes, others should as well because they are based on
the same layout. This also keeps the pipeline from getting slower
as more software is added.
Fix #836.
=> chore(ci): speed up pa11y run

.github/workflows/danger-js.yml
Run danger just on pull_request_target for now, that's
where we have the right token.
=> chore(ci): run danger just on pull_request_target.

.circleci/config.yml
rsync is no longer used anywhere.
=> chore(ci): don't install rsync

assets/index.js, package.json
Removes explicit import of moment.js
However, it will be included in the bundle because it is used by chart.js, but it doesn't seem to be a direct dependency of developers.italia
* [ x] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [ x] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [ x] Have you successfully ran tests with your changes locally?
=> Remove moment.js from package.json

README.md
* switch the netlify badge with the official vercel one
=> chore: switch netflify with vercel badge

_posts/it/2018-03-12-code-hands-on-laboratori-aperti-per-la-milano-digital-week.md
Don't use the HTML entity in the news post so we don't have to use
dangerouslySetInnerHTML in the search engine.
Fix #895.
=> fix: don't use HTML entity in front matter block

package-lock.json, package.json
Dependabot cannot update prismjs to a non-vulnerable version. This PR pins `prismjs` version to 1.23.0
=> Security: upgrade prismjs to 1.23.0

_platforms/en/spid.md, _platforms/it/spid.md
* chore: older ShibProxy is in EOL, a new shibboleth spid proxy here
* added AgID SPID HelpDesk page
In particular, this shibboleth idp project is hosted to a third-party github repository
=> updated shibboleth proxy in SPID page

_platforms/en/spid.md, _platforms/it/spid.md
* fix: spid helpdesk  
* fix: HelpDesk Page is not intended to developers an email contact has been adopted instead.
=> SPID AgID HelpDesk mailto href

_layouts/post.html
=> fix(news): don't show topics section if there are no tags

Makefile
Use --trace in jekyll serve so any errors are clearly printed when the
development environment is started.
=> chore: use --trace in jekyll serve

assets/js/github-issues.js, en/issues.md, it/attivita.md
Add new open issues pages in both languages (/it/attivita, /en/issues)
Fix #970.
=> feat: add new open issues pages

_data/apis.yml
cambio da mibact a mic per l'URL in modo da riflettere la nuova sigla
=> mibact->mic

assets/js/api/elasticSearchUtils.js
Use Elastic's scripting to sort alphabetically and provide a fallback if
localizedName for the current language is not present.
I don't know if that's the smartest way to do it, but it's A solution.
Fix #882
=> fix: make alphabetical order work in search engine

assets/js/components/Catalogue/CatalogueContainer.js, assets/js/components/Catalogue/CatalogueSort.js, assets/js/components/Catalogue/CatalogueSort.test.js
This PR improves the browsing experience when no explicit search term has been submitted
In particular, the sorting criteria is being defaulted to "release date"
Fixes #1022
=> feat: sort software by release_date when no search term is available

en/legal-notice.md, it/note-legali.md
Update Italian and English legal notices citing the DTD as owner.
Use the Italian text for English as well until there's a translation.
=> chore: update Italian and English legal notices

en/privacy-policy.md, it/privacy-policy.md
Remove link to the proprietary Google Analytics browser extension
from the privacy policy page.
=> chore: remove link to proprietary Google tool

_includes/banner-newsletter.html
Use "mailing-list" instead of "newsletter" for uniformity.
=> fix: use "mailing-list" as the fragement for mailing list URL

assets/js/api/elasticSearchUtils.js, assets/js/components/Catalogue/CatalogueContainer.js, assets/js/contexts/searchContext.js, assets/js/hooks/useSearchEngine.js, assets/js/utils/urlSearchParams.js
Add the capability of searching for PNNR related software.
We came up with the convention that Italian publiccode.yml files can put
"tags" in "description.it.features" to mark software that help Public administrations
with the PNRR (https://www.governo.it/sites/governo.it/files/PNRR.pdf).
We have three kinds of tags:
1. "PNRR" as the general tag
It can be searched by adding "pnrr=1" to the query string
2. "PNRR/Beneficiari/$TARGET_NAME" the target the software is made for,
fe. "Scuole" (Schools), "Comuni".
It can be searched by adding "pnrr_target=$TARGET_NAME" to the query
string (case sensitive)
3. "PNRR/Misura/$NUMBER" the PNRR measure, fe "1.4.1"
It can be searched by adding "pnrr_measure=$NUMBER" to the query
string
Fix #1207
cc @mfortini
=> feat: add PNRR search to the search engine

_config.yml
Automatically assign the Sendportal "Des+Dev" tag when the user
confirms the registration.
Fix #1213.
=> feat(mailing list): assign the "Des+Dev" tag when registering

assets/js/components/MailingList/MailingListConfirmation.js
Make it clear in the mailing list confirmation page that the user
will receive both Developers and Designers Italia emails.
=> chore: better text on mailing list confirmation

Dangerfile.js
Commitlint was kind of a failure and it ends up just being an annoyance, sadly.
=> chore(ci): relax commitlint severity to warning

_includes/home-software-categories.html
The "More tags" button on the homepage makes the view scroll to top when clicked.
Removing href="#" prevents this behavior.
Fixes #1204
=> fix: "More tags" button scrolls to top

Gemfile.lock, Makefile
bundler > 2.1 needs to be instructed on what architectures to use when fetching the binary packages, otherwise it'll always try to compile the gem.
The Vercel preview uses bundler 2.3, so let's bump the version.
=> chore(build): fix the build when using bundler > 2.1

assets/js/api/elasticSearchUtils.js
`categories` was [already supposed to be a keyword](https://github.com/italia/publiccode-crawler/blob/legacy/elastic/elastic.go#L198-L200), but it isn't in production for some reason.
Elastic's mapping update doesn't work for fields already indexed, so let's add a `keyword` subfield instead of re-indexing everything - which is error prone and can cause downtime.
Fix #1203, Fix #1231
cc @libremente
=> fix: use the keyword field to filter categories

en/reuse/publication.md, it/riuso/pubblicazione.md
publishers.thirdparty.yml is on the legacy branch, which is from the non-API crawler is build for the time being.
=> content: update link to publishers.thirdparty.yml

Dockerfile, docker-compose.yml
* use explicit repo (docker.io) for containers in docker-compose and Dockerfile
this enables podman compatibility in image pulling
* [x ] Have you successfully ran tests with your changes locally?
=> chore(container): use explicit repo

docker-compose.yml
`elasticsearch`  service was missing in docker-compose
* [ *] Ready for review! :rocket:
`elasticsearch`  service was missing in docker-compose
=> fix(container): missing es in docker-compose

_data/publishers.yml
Import publishers.yml into this repo from
https://github.com/italia/publiccode-crawler/blob/1113650a8dc429cb072d0d7eb1b058821617c564/publishers.yml
See also ed6bdaa833e8 and
https://github.com/italia/publiccode-crawler/issues/298
=> chore: import publishers.yml from publiccode-crawler

en/how-to-participate.md, en/how.md, it/come-lo-uso.md, it/come-partecipo.md
Remove API section as it will be replaced by the public API catalog from PDND.
Update the content in How to use.
=> content: remove report API section and update content

_platforms/en/cie.md, _platforms/en/spid.md, _platforms/it/cie.md, _platforms/it/spid.md
* add spid-php as SDK for CIE
* add spid-php as Proxy for SPID and CIE
* add spid-cie-oidc-php as SDK OIDC for CIE
* add spid-cie-oidc-php as Proxy for SPID and CIE
=> Add spid-php and spid-cie-oidc-php as SDK and Proxy into SPID and CIE Resources

assets/scss/main.scss, assets/scss/swagger-ui-overrides.scss
Locally override the CSS and have wider schemas in the example section
Fix #1305.
=> fix: swagger-ui rendering of model schemas

.github/workflows/crawl.yml
`CRAWLER_DATADIR` is now `DATADIR`, but it has a sane default anyway, so we can skip it.
=> chore: adapt for publiccode-crawler v4.0.0

_layouts/software-details.html
Add a link to show all the categories in the software page and display
at least five categories by default.
Fix #1230.
=> feat: add a way to show all the categories in software page

_includes/home-listing-items.html
This PR fixes the title displayed for each platform of the related home page section.
Fixes #1454
=> Display correct platforms titles

assets/js/services/searchEngine.js, assets/js/services/searchEngine.test.js
The catalog currently crashes with an error `Cannot read properties of undefined (reading 'shortDescription')` when displaying software that uses country-specific language tags in their `publiccode.yml` files.
This happens because the code only looks for exact language matches (e.g., 'it') and doesn't recognize extended language tags like 'it-IT', even though these are valid according to the IETF BCP 47 standard and explicitly permitted in the publiccode.yml spec.
I've implemented a more robust language selection algorithm that:
1. First tries an exact match with the current language
2. Then looks for variants of the same base language (e.g., 'it-IT' when the base is 'it')
3. Falls back to standard languages (first 'en', then 'it')
4. As a last resort, uses any available language …
=> fix: handle IETF BCP 47 language variants in publiccode descriptions

_layouts/brand-pa.html, _layouts/software-details.html
Software like *PCS-MIT* with descriptions in `it-IT` format don't display descriptions on detail pages because Jekyll templates only check exact language matches (`it`).
Add BCP 47 language variant fallback logic to automatically resolve:
- `it-IT` → `it`
- `en-GB` → `en` 
- `fr-FR` → `fr`
- etc.
- **software-details.html**: Add fallback for main descriptions, variants, and related software
- **brand-pa.html**: Add fallback for PA software listings
```liquid
{% assign description = page.publiccode.description[active_lang] %}
{% unless description %}
{% for lang_key in page.publiccode.description %}
{% assign lang_base = lang_key[0] | split: '-' | first %}
{% if lang_base == active_lang %}
{% assign description = lang_key[1] %}
{% break %}
{% endif %}
{% endfor %}
{% endunless %}
```
Fixes …
=> feat: add BCP 47 language fallback support in Jekyll templates
