italia/developers.italia.it

_pages/it/note-legali.md

there is a permanent redirect for both websites, but it's nice to show that you are paying attention to those kind of details! :)

nit: replace http with https

---

_data/l10n.yml
_data/menu_items.yml
_faqs/en/1.yml
_faqs/en/10.yml
_faqs/en/20.yml
_faqs/en/30.yml
_faqs/en/40.yml
_faqs/en/50.yml
_faqs/en/60.yml
_faqs/en/70.yml
_includes/footer--simple.html
_pages/en/credits.md
_pages/en/faq.md
_projects/en/18app.md
_projects/en/anpr.md
_projects/en/cie.md
_projects/en/fatturapa.md
_projects/en/pagopa.md
_projects/en/spid.md

Translated most of the website to English (british) language

EN-GB translation

---

_config.yml

Quick fix for issue #24 (cookiebar - Link "Privacy policy" not defined), IT only

---

_data/menu_items.yml
_includes/linklist.html
_includes/scripts.html
_layouts/home.html
_sass/_developer.scss
assets/scripts/main.js

Fix menu link

---

_projects/it/pagopa.md

Questo commit aggiunge i primi 3 documenti alla pagina di progetto legata a PagoPA.

Pubblicazione documentazione PagoPA

---

_plugins/GithubImporter.rb

GitHub API returns max 100 repositories per query, implement pagination.
Also limit query to public repositories.

Bugfix: incomplete issue list

---

_posts/it/2017-10-03-hack-developers-ti-aspettiamo.md

Articolo di blog sulla newsletter inviata il 3 ottobre per hack.developers

Aggiunta notizia del 3 ottobre sull'hackathon al blog

---

_posts/it/2017-10-11-hack-developers-come-e-andata.md

Aggiunge articolo al blog, dalla newsletter inviata l'11 ottobre

Aggiunge notizia 11 ottobre post hackathon al blog

---

_posts/it/2017-11-08-hack-developers-tutti-i-progetti-vincitori-del-code-sprint.md

Aggiornamento con il testo dell'ultima newsletter inviata

Post di aggiornamento del blog developers 8/11

---

_projects/it/pagopa.md

Modifica links Docs PagoPA

---

_projects/it/anpr.md
_sass/_developer.scss

Fix #100 
Bisogna testare il form una volta messo online

Some cosmetic fix to the newsletter form in the ANPR project page

---

_posts/it/2018-02-21-developers-italia-al-google-summer-or-code.md

Come da newsletter inviata il 21/02

Aggiunge notizia su GSoC

---

_posts/it/2018-03-12-code-hands-on-laboratori-aperti-per-la-milano-digital-week.md

Crea notizia su Code hands-on Milano Digital Week

---

_projects/it/devops.md

una prima bozza del progetto/community devops

Pagina Community devops

---

_pages/en/gsoc-ideas.md

This PR adds a new proposal for the GSoC program as discussed with @ruphy on Slack. 
Thanks!

New GSoC proposal

---

_data/apis.yml

Tradotta la descrizione delle API.

Fix API description: siope+ e RNDT

---

_data/apis.yml

- rimosso Fatture e Corrispettivi
- corretti loghi
- indicato "comingsoon: true" su RegioneLombardia

Rimosso Fatture e Corrispettivi. Corretti loghi.

---

_data/apis.yml

- images from teamdigitale/api-openapi-samples
- renamed siope to siopeplus

Relocate images and files

---

_data/apis.yml

Add Parchi Lombardi.

---

_data/menu_items.yml
_layouts/api.html

Riscrive i link della sottosezione API a partire dalla root

Update API links

---

_data/menu_items.yml
_plugins/data_page_generator.rb

[#158118666] Modified the data-page-generator to manage also the "lang" attribute.
Fix, WIP, the english nav menu data.

Page generator lang fix

---

_config.yml
_data/actors.yml
_data/l10n.yml
_data/menu_items.yml
_includes/github_team_members.html
_includes/linklist.html
_includes/project-apis.html
_includes/project-resources.html
_layouts/project.html
_pages/it/piattaforme.md
_projects/it/anpr.md
assets/main.scss

[#158465578] Redesign for the Platform layout (formely Project page)

[#158465578] Redesign for the Platform layout (formely Project page)

---

_includes/home-listing-items.html
_layouts/projects.html

FIX the url of projects in listing (projects page & home)

FIX this fix put in the right place the url of a project listed

---

_layouts/api.html
assets/main.scss

[#158831640] Have a new listing page for APIs

[#158831640] Have a new listing page for APIs

---

_layouts/software-details.html

This PR solves [[#158835731]](https://www.pivotaltracker.com/story/show/158835731) following the language fallback style in the page.

[#158835731] Languages fallback software details page.

---

_includes/alternate-blocks.html
_includes/card.html
_includes/footer--simple.html
_includes/home-listing-items.html
_includes/pair-blocks.html
_layouts/api.html
_layouts/home.html
_layouts/posts.html
_layouts/posts_by_tag.html
_layouts/projects.html
_pages/it/chi-siamo.md
assets/main.scss

[#158973520] Some cosmetic fixes for a better view on smartphones

[#158973520] Some cosmetic fixes for a better view on smartphones

---

_layouts/software-details.html

Add percentage ('%') sign to software detail vitality score.

---

_layouts/brand-pa.html
_pages/it/bagnacavallo.md
assets/main.scss

Dummy page with fixed url : /it/bagnacavallo

[#158524390] "Pagina brandizzata" 

---

_data/l10n.yml
_layouts/software-details.html
_sass/software-detail.scss
assets/main.scss

[#158865674] Tooltip message for the Software detail page

[#158865674] Tooltip message for the Software detail page

---

swagger/README.md
swagger/index.js
swagger/openapis.js
swagger/package-lock.json
swagger/package.json
swagger/swagger.html

The new `Parcel` bundler version  changed the scope of global defined variables.

Update API section

---

_pages/en/gsoc-ideas.md

New proposals daf

---

_pages/en/gsoc-ideas.md

New GSoC ideas for designers

---

_data/l10n.yml
_data/tools.yml
_faqs/en/1.yml
_faqs/en/10.yml
_faqs/en/20.yml
_faqs/en/30.yml
_faqs/en/50.yml
_faqs/en/60.yml
_faqs/en/70.yml

Fixing some typos and broken links in the FAQs.

Fix FAQ section

---

_pages/en/gsoc-ideas.md

Adding the 2019 GSoC proposals for the API project.

New GSoC proposals API

---

_posts/it/2019-03-06-developers-italia-al-google-summer-or-code-2019.md

Aggiunge news alla partecipazione di Developers al GSoC 2019

Crea nuovo articolo GSoC 2019

---

_data/l10n.yml
_data/menu_items.yml
_includes/banner-discuss.html
_includes/lang_switch.html
_layouts/home.html
_layouts/platform.html
_pages/en/about.md
_pages/en/api.md
_pages/en/contacts.md
_pages/en/get-involved.md
_pages/en/how-to-participate.md
_pages/en/how-to-use-it.md
_pages/en/how.md
_pages/en/news.md
_pages/en/platforms.md
_pages/en/re-use-software.md
_pages/en/reuse.md
_pages/en/software.md
_pages/it/software.md
_platforms/en/18app.md
_platforms/en/anpr.md
_platforms/en/cie.md
_platforms/en/daf.md
_platforms/en/docs-italia.md
_platforms/en/fatturapa.md
_platforms/en/pagopa.md
_platforms/en/spid.md
_platforms/it/18app.md
_platforms/it/anpr.md
_platforms/it/spid.md

---
WIP
---
Translation into english

En translation

---

_pages/en/gsod-ideas.md

New page for GSoD.
Add your contribution and push in this branch called `gsod-ideas-page`.
Thank you

Add new GSoD page

---

_includes/platform-resources.html
assets/main.scss

Using Bootstrap Italia SVG sprite for projects' resources

---

_posts/en/2018-05-23-un-ambiente-di-test-aperto-a-tutti-per-anpr.md
_posts/en/2019-03-06-developers-italia-al-google-summer-of-code-2019.md
_posts/it/2018-05-23-un-ambiente-di-test-aperto-a-tutti-per-anpr.md
_posts/it/2019-03-06-developers-italia-al-google-summer-of-code-2019.md

Translation of some news into English:
@alranel

News translation into English

---

_data/apis.yml

adds comingsoon INGV earthquake events API #351

Add: INGV earthquake events API #351

---

_data/apis.yml

- align title with the latest ingv spec
- the title is now more readable

Unlock and align INGV API  title with the latest spec.

---

_config.yml
_includes/banner-newsletter.html
_layouts/home.html
_layouts/internal-simple.html
_pages/en/contacts.md
_pages/it/contatti.md

As of now, the newsletter forms in the home page and in the contacts page do not work as intended.

Fix newsletter forms

---

swagger/components/Hero.js

Add a comment to explain usage of project.js

---

_data/apis.yml

removes coming-soon instead of falseing it.

Remove coming-soon

---

_posts/it/2019-09-03-Una-call-per-la-community-di-Developers-Italia.md

Crea news sulla prima community call

Crea news su prima community call

---

_posts/it/2019-10-01-I-progetti-di-Developers-Italia-al-Google-Summer-of-Code.md

Con la descrizione dei progetti del GSOC

Crea notizia su Developers del 1 ottobre

---

_pages/en/reuse/acquisition.md
_pages/en/reuse/publication.md
_pages/it/riuso/acquisizione.md
_pages/it/riuso/pubblicazione.md

This PR:
* adds the explicit title in the reuse pages. 
@alranel please let me know if this makes more sense, right I feel a bit lost without the page title.

Add title to reuse pages

---

assets/scripts/esDevelopersItaliaQuery.js

Hello, this is PR solves the above issue.
I also suggested a slightly different translation for the english part, I hope it's fine.
Thanks for your time!

Fix #392 (case of lack of reserched terms)

---

_pages/it/info-privacy-communitycall.md

Add info privacy community call

Add info privacy cc

---

_data/apis.yml

Adds the API for querying the data in the ANPR dashboard.
preview here: https://deploy-preview-436--developers-italia.netlify.com/it/api/
@mccalv is that ok?

Add anpr-dashboard API

---

_data/crawler/amministrazioni.yml
_data/l10n.yml
_includes/pa-listing.html
_includes/pair-blocks.html
_includes/sw-pair-blocks.html
_layouts/search.html
_layouts/software-details.html
_layouts/software-sub-category.html
_layouts/software.html
_pages/en/software.md
_pages/it/software.md
assets/scripts/esDevelopersItaliaQuery.js

New Software page
- Fixes #393 reuse software are linked to main PA organisation
- Software page redesigned to improve readability and UX #331 
- Two big blocks for reuse and open software
- One more row with most virtuous administration
This PR is still under evaluation, we are discussing on how we can improve design and usability.

New software page

---

_layouts/software-details.html

This PR:
* checks whether a contractor's website is present before printing it
@sebbalex

Remove href when maintainer website is not present

---

_data/l10n.yml
_includes/dependency.html
_layouts/software-details.html
assets/main.scss

This PR aims at solving #451. Still WIP

Fix software dependencies visualization in catalog

---

_includes/software-listing.html
_layouts/software-details.html
_templates/search.handlebars
assets/scripts/esDevelopersItaliaQuery.js
assets/templates/search.tpl.js

As for #461 SVG logo were not displayed for Github repository since they had a not image related mime type. By using `sanitize=true` parameter they are forced to use the specific SVG mime type.

Support for SVG logo for GitHub

---

.gitignore
_data/l10n.yml
_layouts/software-details.html

This PR:
* inserts a check on false array
* inserts the display of the new section called `conforme`. 
@sebbalex

Insert conforme section

---

_posts/it/2019-11-11-Call-Developers-Italia-il-programma-di-abilitazione-al-cloud.md

News developers per la community call dell'11 novembre

News sulla nuova community call di developers

---

_templates/search.handlebars
assets/templates/search.tpl.js

Expand the interactive area in search results.

---

_posts/it/2019-11-14-terminato-hacktoberfest-tiriamo-le-somme.md

This PR:
* inserts a news about hacktoberfest

Add hacktoberfest end news

---

Gemfile.lock
_includes/header-pa.html
_includes/header.html
_includes/lang_switch.html
assets/main.scss

Fix #308 vertical alignment of header buttons

---

package.json

Bump BSI to 1.3.9, fixes #486 
@sebbalex

Bump bootstrap-italia to 1.3.9

---

package-lock.json
package.json

updates chart.js
#496 
2.8.0 -> 2.9.3
previous version -> 2.8.0
wanted version on `npm outdated`-> 2.9.3

update package chart.js

---

_includes/home-listing-sw.html

- Fixes #461
- Set default image placeholder when it is not available

#461 Fix and default image placeholder

---

_data/menu_items.yml
_pages/en/gsoc-ideas.md
_pages/it/idee-gsoc.md

This PR:
* Adds the italian GSoC page
* switches its layout to internal-simple
* adds the menu entry
Fixes #502 and #507

New gsoc page

---

_layouts/search.html
assets/scripts/esDevelopersItaliaQuery.js

Sort by filter and results number are disappeared from view, this is mostly due to previous bugfix.
#506

Fixes #506 again

---

_data/apis.yml

adds the Regione Umbria API with dati covid.
@ggentili

Aggiunta API covid-19 Regione Umbria

---

assets/main.scss

Fix: #549. Fix icon height in api/.

---

_pages/it/privacy-policy.md

This PR:
* fixes some typos in the privacy-policy page
Fixes #553

[#553] Switch cookies to cookie

---

_data/footer_links.yml
_includes/footer--simple.html

This PR:
* Adds translated links for the footer section
* Adds logic to handle such translated links

[#559] Add footer links translation logic

---

_data/l10n.yml

This PR is intended to make the vitality index documentation clearer. 
Tackling #268

Translate vitality index documentation. 

---

CONTRIBUTING.md

This PR:
* adds the CONTRIBUTING file

[#565] Add CONTRIBUTING file

---

package-lock.json
package.json

As already mentioned in #579, this PR tackles:
* bumps BSI to 1.3.10
* adds some information regarding the project in the `package.json` file
- Fixes #579

[#579] Bump BSI to 1.3.10

---

README.md

Github pages pointer has changed from `docs` folder to `gh-pages` branch

Update readme, new destination for GH pages

---

assets/scripts/esDevelopersItaliaQuery.js

As already mentioned in #602 , this PR tackles:
* input in search box were not sanitized and expose to a XSS attack.
- Fixes #602

input on search box were not sanitized

---

_includes/display-logo.html
_includes/head.html
_includes/home-listing-sw.html
_includes/software-listing.html
_layouts/brand-pa.html
_layouts/software-details.html
_pages/en/privacy-policy.md
_pages/it/privacy-policy.md
assets/scripts/logos.js

This PR:
* unifies every way to display logos in the various layouts used in the website.
Connected issues:
* Fixing #481

[#481] Unifying logos display in all layouts

---

_data/l10n.yml
_layouts/software-details.html
_sass/software-detail.scss

As already mentioned in #463, this PR tackles:
* long supported languages list are limited to max 10 results, when more a "Show all" button will appear.
- Fixes #463

vertical scroll for sw supported languages

---

docker-compose.yml

As already mentioned in #619, this PR tackles:
* remove assets volume from docker-compose
- Fixes #619

removing assets volume from docker-compose

---

_layouts/search.html
_layouts/software-details.html
_sass/search-page.scss
assets/scripts/esDevelopersItaliaQuery.js
assets/scripts/esQuery.config.js

As already mentioned in #636, this PR tackles:
* audience scopes filter in search page.
- Fixes #636

Add search audience scope filters

---

_data/faq.yml

As already mentioned in #268, this PR:
* introduces some documentation regarding the vitality index in the FAQ section. 
In particular, I believe that proper documentation regarding the operations carried out should be written on a MD file to be stored in the backend repo and linked from this FAQ.
- This PR is linked with [this PR](https://github.com/italia/developers-italia-backend/pull/174). As such, please merge that one before in order to avoid htmlproofer errors or other 404. 
- Fixes #268

[#268] Add vitality index explanation

---

Dockerfile

Fix the docker build broken in #657.

Fix broken Docker build.

---

.circleci/config.yml
scripts/github_importer.rb

This fixes the build failing and the contacts page.

Fix file format outputted by github_importer.

---

_includes/footer--simple.html
_includes/header.html
_includes/social-icons.html
assets/scss/main.scss

Fix footer icons not displaying properly.

---

.circleci/config.yml
package-lock.json
package.json

The current deploy job is keeping old files around, the gh-pages
package should do the right thing instead.

Use gh-pages package to push to GitHub Pages.

---

assets/js/esDevelopersItaliaQuery.js
assets/js/search.handlebars
assets/scss/main.scss

[#368] Search thumbnail draft

---

assets/js/github-issues.js

As already mentioned in #675 , this PR tackles:
* This will handle permalink which will filters data by type
* inputs are sanitized
- Fixes #675

permalink for todo page which filter data by type

---

_layouts/github-issues.html
assets/index.js
assets/js/github-issues.js
scripts/github_importer.rb
webpack.common.js

Restore the style of selects in /en/to-do.

---

README.md

This PR adds a simple link to our Slack channels.
- Fixes #172

Add Slack link to README

---

.circleci/config.yml

Have gh-pages deploy dotfiles as well.

---

.circleci/config.yml

Make GitHub serve dotfiles.

---

_posts/it/2020-10-01-developers-italia-hacktoberfest-2020.md

This PR adds the Hacktoberfest 2020 news.

Add new hacktoberfest news

---

_data/l10n.yml
_includes/share.html

Shows small text when hovered on links to describe the action.
As already mentioned in #725 , this PR tackles:
* Adds hover text for links in the news page.
- Fixes #725

[#725] Added hover text on links in news page

---

assets/js/esDevelopersItaliaQuery.js
assets/js/logos.js
assets/js/search.handlebars

When the software logo is not available in the search page,
fallback to a default image.
Fix #700.

Fallback to placeholder logo in search page.

---

_includes/header.html
assets/scss/main.scss

As already mentioned in #736, this PR tackles:
* Counter-intuitive arrow icons in the header
- Fixes the alignment of the Counter-intuitive arrow for mobile screens, Modified CSS supports screens up to 412px.
Screenshot Resolution: 411 x 731px

[#736] - Counter-intuitive arrow icons in the header

---

assets/js/esDevelopersItaliaQuery.js

As already mentioned in #757 , this PR tackles:
* Some description are not localized and accessing `shortDescription` caused that fail.
- Fixes #757

Some description are not localized in both languages

---

_includes/header.html
assets/scss/main.scss

As mentioned in issue #491 the tagline/agenda was also getting selected while hovering over the logo or the main title. This has been resolved.
Checklist
- [ x ] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [ x ] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ x ] Have you written new tests for your core changes, as applicable?
- [ x ] Have you successfully ran tests with your changes locally?
- [ x ] Ready for review! :rocket:

#491 issue of the tagline getting highlighted solved. 

---

_includes/home-software-categories.html
_layouts/platforms.html
_platforms/it/fatturapa.md
assets/scss/main.scss

As already mentioned in #726 , this PR tackles:
- Adds a short description to platforms thumbnails using the software description that were already present in the project
- Fixs also the layout of the description on mobile devices
- Fixes #726

[#726] Platforms thumbnails short description

---

assets/scss/main.scss
it/software.md

As already mentioned in #722/ 767, this PR tackles:
* This fixes the button background color on it/software
In particular, on hover the background now changes to your standard site blue color, while the button text is white and very visible. 
*PLEASE IGNORE/ DELETE PREVIOUS PULL REQUEST AS THIS ONE IS A CLEANER FIX*
- Fixes # 722
- Fixes #767

Issue #722/ 767 actual fix

---

_includes/search-modal.html
assets/js/esQuery.js

As already mentioned in #718, this PR tackles:
Fix the search input autofocus, triggering the focus event when the user clicks on the search icon, so the user can start to directly type as requested
- Fixes #718

[#718] fix search input autofocus

---

_includes/banner-discuss.html

Resubmitting #784, because I closed it by mistake by force pushing.
Fix #783.

Fix homepage boxes too narrow at certain resolutions

---

_data/apis.yml

- removes retired API
@sebbalex merge if ok.

Remove retired DAF API

---

_posts/it/2020-11-11-terminato-hacktoberfest-2020.md

This PR:
* adds the final Hacktoberfest 2020 news

Add hacktoberfest news

---

_posts/it/2018-05-23-un-ambiente-di-test-aperto-a-tutti-per-anpr.md

As already mentioned in #802, this PR tackles:
* switches a tag from `open-source` to `opensource`
- Fixes #802

[#802] Switch open-source to opensource in tags

---

_data/l10n.yml
_layouts/software-details.html
assets/scss/main.scss
assets/scss/software-detail.scss
it/riuso/acquisizione.md
it/riuso/dichiarazione.md
it/riuso/pubblicazione.md

feat: add pages to guide through the reuse declaration procedure

---

_data/faq.yml
it/riuso/acquisizione.md
it/riuso/dichiarazione.md
it/riuso/pubblicazione.md

This PR:
* adds the FAQ related to the reuse declaration
* fixes some typos

Add reuse declaration FAQ

---

_posts/en/2018-05-23-a-testing-environment-for-anpr.md
_posts/en/2019-03-06-developers-italia-at-google-summer-of-code-2019.md
_posts/it/2017-02-24-lancio.md
_posts/it/2017-05-25-pubblicata-roadmap-spid.md
_posts/it/2017-06-01-vuoi-lavorare-developers-italia.md
_posts/it/2017-07-27-hack-developers-hackathon-per-pubblica-amministrazione.md
_posts/it/2017-09-07-hack-developers-meetup.md
_posts/it/2017-10-03-hack-developers-ti-aspettiamo.md
_posts/it/2017-10-11-hack-developers-come-e-andata.md
_posts/it/2017-10-23-hack-developers-ecco-i-vincitori-fast-rabbit.md
_posts/it/2017-11-08-hack-developers-tutti-i-progetti-vincitori-del-code-sprint.md
_posts/it/2018-02-21-developers-italia-al-google-summer-or-code.md
_posts/it/2018-03-07-ti-presentiamo-il-nuovo-docs-italia.md
_posts/it/2018-03-12-code-hands-on-laboratori-aperti-per-la-milano-digital-week.md
_posts/it/2018-04-05-linee-guida-in-consultazione.md
_posts/it/2018-04-16-linee-guida-su-acquisizione-e-riuso-del-software.md
_posts/it/2018-05-16-un-webinar-per-le-software-house-sull-acquisizione-e-il-riuso-del-software.md
_posts/it/2018-05-23-un-ambiente-di-test-aperto-a-tutti-per-anpr.md
_posts/it/2019-03-06-developers-italia-al-google-summer-of-code-2019.md
_posts/it/2019-09-03-una-call-per-la-community-di-Developers-Italia.md
_posts/it/2019-10-01-I-progetti-di-Developers-Italia-al-Google-Summer-of-Code.md
_posts/it/2019-10-11-Appuntamento-in-call-con-Developers-Italia.md
_posts/it/2019-10-23-Developers_Italia_a_Codemotion_2019_ci_vediamo_a_Milano.md
_posts/it/2019-10-28-Call-Developers-Italia-parliamo-di-design-dei-servizi-pubblici.md
_posts/it/2019-11-11-Call-Developers-Italia-il-programma-di-abilitazione-al-cloud.md
_posts/it/2019-11-14-terminato-hacktoberfest-tiriamo-le-somme.md
_posts/it/2020-10-01-developers-italia-hacktoberfest-2020.md
_posts/it/2020-11-11-terminato-hacktoberfest-2020.md

SVGs in Twitter cards are not supported:
https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup
Fix #776.

fix: use PNG images: SVGs are not supported by Twitter

---

_layouts/platforms.html
assets/js/search.handlebars

As already mentioned in #ISSUE_NUMBER, this PR tackles:
* Sorry for my other pull request, now i delete all branch and i created a new fork and new branch
* I try another time to fix them, tell me if now is ok
**I have a problem to see the software page, because when i search "rer flesk" the page return me** " _Ops! Nessun risultato trovato
La ricerca non ha prodotto nessun risultato. Prova un'altra chiave di ricerca._ " **
- [ X] I followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md)
- [ X] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ X] Have you written new tests for your core changes, as applicable?
- [X ] Have you successfully ran tests with your changes locally?
- [X ] Ready for review! …

Fix Software name lenght exceeds column width 

---

_posts/it/2020-11-18-nuova-modalita-dichiarazione-riuso.md

This PR:
* adds a new post regarding the novel reuse declaration mode

Add news on new reuse declaration mode

---

_posts/it/2020-11-18-nuova-modalita-dichiarazione-riuso.md

This PR:
* adds two simple links to the social channels.

chore: add links to news

---

_layouts/home.html

As already mentioned in #792, this PR tackles:
* Adds short description to platform items on the home page
- Fixes #792

[#792] feat: Description for platform items

---

_data/people.yml

As already mentioned in #ISSUE_NUMBER, this PR tackles:
* ...
* ...
* ...
- Fixes #

I am back.

---

en/to-do.md
it/cosa-fare.md

Fix the copy in /it/cosa-fare and improve the working and formatting
in both it and en pages.
Fix #826.

fix: right copy in /it/cosa-fare

---

.circleci/config.yml

As already mentioned in #696 , this PR tackles:
* switch circleci ssh key
- Fixes #696

chore: switch circleci ssh key

---

.circleci/config.yml

chore: cache yarn and bundle packages in CI

---

_posts/it/2020-12-15-al-via-survey-community.md

Add news on survey

---

_posts/it/2020-12-29-guida-sviluppo-gestione-software-libero.md

This PR:
* adds a news regarding the publication of the new guide  on free software development.

chore: add news guida software libero

---

_posts/it/2020-12-29-guida-sviluppo-gestione-software-libero.md

fix: switch guida link to stable

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Also fix the link to CONTRIBUTING.md in the PR template.
Fix #823.

chore: update and simplify CONTRIBUTING.md

---

assets/js/swagger-custom.js

chore: remove useless development customisation

---

Makefile

Adds a test runner in the Makefile (used by CircleCI)

feat: add test in Makefile

---

_platforms/it/anpr.md

fix: anpr number

---

.circleci/config.yml

We don't use yarn in this repo, let's name the key in a more generic way.

chore(ci): s/yarn/node_modules

---

_data/l10n.yml
assets/images/something_is_wrong.svg
assets/js/components/Catalogue/CatalogueView.js
assets/js/components/Catalogue/CatalogueView.test.js
assets/js/components/Error.js
assets/js/components/Search/SearchContainer.test.js
assets/js/components/Search/SearchModal.js
assets/js/hooks/useSearchEngine.js
assets/js/hooks/useSearchEngine.test.js
assets/js/utils/__mocks__/l10n.js

Closes #897
Some screenshots when the Elasticsearch client throws an error

feat: show an error message when Elasticsearch is not available

---

assets/js/components/Error.js

Maintenance ended.
This reverts commit 316c75bccc0b00bbe3bbcda31bca932d52b5802e.

feat: remove temporary maintenance banner

---

_posts/it/2019-09-03-una-call-per-la-community-di-Developers-Italia.md
_posts/it/2019-10-11-Appuntamento-in-call-con-Developers-Italia.md
_posts/it/2019-10-28-Call-Developers-Italia-parliamo-di-design-dei-servizi-pubblici.md
_posts/it/2019-11-11-Call-Developers-Italia-il-programma-di-abilitazione-al-cloud.md
_posts/it/2021-02-17-spid-cie-disponibili-nuove-risorse-opensource.md

* fixes some links to the community call privacy policy page
* fixes a typo in the latest article

Fix typos and remove trailing slashes

---

_platforms/it/spid.md

Cleanups, some weblinks have been updated, trello roadmap removed (deprecated).
* cleanup of deprecated SDK
* spid-compliant-certificates in tools

[SPID] aggiornamento riferimenti

---

_platforms/it/spid.md

- minor changes
- a warning message about the nature of dev ita's spid projects

[SPID] fix: added some additional informations

---

_posts/it/2021-03-04-nuovo-motore-di-ricerca.md

* adds a news regarding the new search engine.
Fixes #

Add news on new search engine

---

_platforms/it/noipa.md

This PR adds API section to NoiPA with two references: SPARQL editor and an example written in Python

feat: add API to NoiPA

---

_platforms/it/indicepa.md

This PR refactors indicePA platform

feat: refactoring indicePA platform

---

_platforms/en/cloud.md
_platforms/it/cloud.md

Some minfxies for Cloud Italia platform

Some fixes for cloud italia platform

---

_platforms/it/io.md

feat: refactoring IO

---

_platforms/en/anpr.md
_platforms/it/anpr.md

feat: refactoring ANPR

---

_platforms/it/spid.md

feat: android and ios sdks

---

_config.yml

* changes the Department link
Fixes #947

fix: change Dept link

---

_platforms/en/spid.md
_platforms/it/spid.md

This PR adds:
- [Firefox SAML Tracer plugin](https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/)
- [Chrome SAML](https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace)
- [SAML Developer Tools](https://www.samltool.com)
Fixes #

additional tools for spid

---

assets/js/github-issues.js

Use a regular function as "this" is undefined in the object method
with an arrow function.

fix: restore the functionality of the to-do page

---

_data/faq.yml

* fix difensore civico link
Fixes #958

fix: difensore civico link

---

_platforms/it/cie.md

fix: cie TLS link

---

_includes/header-pa.html
_layouts/default-pa.html

There's no search_form.html layout in the sources.

refactor: remove references to search_form.html

---

_data/apis.yml
_layouts/api.html

As already mentioned in #ISSUE_NUMBER, this PR tackles:
* add cartografia catastale API
- Fixes #773

[WIP] [#773] Cartografia catastale Agenzia delle Entrate

---

_posts/it/2021-05-07-come-progettare-realizzare-sito-web-comune.md

* Add news "Come progettare e realizzare il sito web del tuo Comune?"

Add news corso RTD

---

_layouts/default-pa.html

fix: add search button to PA pages too

---

_layouts/internal-no-intro.html
it/come-partecipo.md

Reword unclear titles and simplify the Get involved page.
Fix #974.

feat: improve the get-involved page

---

_platforms/en/spid.md
_platforms/it/spid.md

SPID Proxy page
* fix: keycloak url

SPID Proxy keycloak

---

_data/l10n.yml
_includes/software-listing.html

fix: localize software-listing.html include.

---

_includes/tiled-gallery.html
assets/js/misc.js

fix: zoom the right image when clicking on screenshots

---

_posts/it/2021-06-01-progettare-sviluppare-erogare-servizi-pubblici-digitali.md

Add news RTD class 2nd edition

Add news RTD class 2nd edition

---

_data/l10n.yml
_includes/card.html
_layouts/post.html
_plugins/localized_dates_filter.rb

fix: localize dates in news pages

---

_platforms/en/spid.md
_platforms/it/spid.md

goodbye spid-testenv2 and thank you for all

fix: spid-testenv2 removed

---

_posts/it/2021-07-02-continuano-le-community-call.md

* ... adding bold in the final call to action
* ...
* ...
* [x ] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [ x] The documentation related to the proposed change has been updated accordingly (also comments in code).
Fixes #

Add new bold

---

_posts/it/2021-07-30-community-call-14-luglio.md

Added an "s" to Developers
* ... correcting a small mistake
* ...
* ...
Fixes #

feat: Update 2021-07-30-community-call-14-luglio.md

---

_platforms/it/pagopa.md

* Fix a small typo
Fixes #1053

fix: typo in pagopa platform

---

_posts/it/2021-09-13-community-call-22-settembre.md

feat: create Update 2021-09-13-community-call-22-settembre.md

---

Makefile
assets/js/github-issues.js
assets/js/platform-activities.js

Fetch github_issues.json from the client instead of getting in on build,
so it's more up to date.

feat: fetch github_issues.json from the client

---

_posts/it/2021-10-05-comincia-Hacktoberfest-2021.md

* switches `aperto` to `libero`

fix: aperto to libero

---

_posts/it/2021-11-12-Community-call-gestire-soluzione-riuso.md

feat: create 2021-11-12-Community-call-gestire-soluzione-riuso

---

_platforms/en/cie.md
_platforms/it/cie.md

(gonna squash the second commit on merge)

fix: links in CIE page, as they changed the site

---

_platforms/en/spid.md
_platforms/it/spid.md

* An imprecise description for the AspNetCore SDK
AspNetCore SDK description fixed

AspNetCore SDK description fix

---

_posts/it/2022-02-10-Riparte-survey-dedicata-alla-community.md

feat: create 2022-02-10-Riparte-survey-dedicata-alla-community

---

_posts/it/2022-02-22-come-si-realizza-design-servizi-pubblici.md

feat: create come-si-realizza-design-servizi-pubblici

---

_platforms/en/designers.md
_platforms/it/designers.md

Update Designers platform

---

_posts/it/2022-02-25-community-call-egovernment-benchmark.md

feat: Create community-call-egovernment-benchmark

---

_layouts/platform.html
_platforms/it/dgc.md

* add hide_activities attributes to platforms in order to hide activities link

feat: add hide_activities attributes to platforms

---

_posts/it/2022-03-11-Community-lab-scopriamo-Bootstrap-Italia-2.0.md

-scopriamo-Bootstrap-Italia-2.0.md
* ...
* ...
* ...
Fixes #

feat: Create community-lab-scopriamo-Bootstrap-Italia-2.0.md 

---

_posts/it/2022-03-15-iniziano-lavori-SDK-SPID-CIE.md

feat: create 2022-03-15-iniziano-lavori-SDK-SPID-CIE

---

_posts/it/2022-03-15-iniziano-lavori-SDK-SPID-CIE.md

chore: add reference to Italian version in news post and fix typo

---

_posts/it/2022-03-25-community-call-sinergia-universita-pa.md

@bfabio titolo da definire
* ...
* ...
* ...
Fixes #

feat: Create 2022-03-25-community-call

---

_posts/it/2022-04-05-guida-software-libero.md

@bfabio 
* ...
* ...
* ...
Fixes #

feat: Create 2022-04-05-guida-software-liber

---

_posts/it/2022-04-08-community-lab-UI-Kit-introduzione-design-token.md

2022-04-08-community-lab-UI-Kit-introduzione-design-token.md
@bfabio 
* ...
* ...
* ...
Fixes #

feat: Create 2022-04-08-community-lab-UI-Kit

---

.github/workflows/publish.yml

chore: add ElasticSearch credentials in the publish action

---

.github/workflows/publish.yml

fix: add Elastic env variables to the right build step

---

_posts/it/2022-05-31-vieni-a-forum-pa.md

@bfabio 
* ...
* ...
* ...
Fixes #

feat: Create 2022-05-31-vieni-a-forum-pa.md

---

_data/l10n.yml
assets/js/components/MailingList/MailingListSubscribe.js

The mailing list is shared with Designers Italia, mention that in the copy.

chore: mention Designers Italia as well in mailing list subscription

---

_platforms/it/fse.md

Update fse.md per review content

---

it/riuso/pubblicazione.md

Add PNRR instructions, see #1249

---

_platforms/en/io.md
_platforms/it/io.md

This commit translates the IO app page in English.
* [ x] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/master/CONTRIBUTING.md)
* [ x] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [ x] Have you written new tests for your core changes, as applicable?
* [ x] Have you successfully ran tests with your changes locally?
Fixes #1212

English translation for the "IO app" page.

---

_platforms/it/fse.md

This PR fixes the build error for the FSE page:
```
Error: YAML Exception reading /home/runner/work/developers.italia.it/developers.italia.it/_platforms/it/fse.md: (<unknown>): did not find expected key while parsing a block mapping at line 20 column 3
```

Typo resulting in block expansion issue

---

Makefile
_platforms/it/fse.md

* pubblicazione piattaforma FSE per fornitori
Fixes #

Per pubblicazione fornitori

---

_platforms/it/fse.md

descrizione link con typo
@libremente 
@ruphy : non ho capito se c'era qualcosa di intenzionale e non finito che contenesse quel "meta" se no per me è da togliere :)

fix: typo in fse.md

---

en/privacy-policy.md
it/privacy-policy.md

chore(content): update privacy policy date

---

_platforms/it/fse.md

link for slack registration in fse

feat(link): link for slack registration in fse

---

_platforms/en/io.md
_platforms/en/pagopa.md
_platforms/it/io.md
_platforms/it/pagopa.md

New content for pagoPA and IO platforms, both in english and italian.
* Description now reflects the right owners (PagoPA S.p.A.)
* Documentation now refers to the latest updates

docs: pages update (PagoPA)

---

_platforms/it/fse.md

fse platform: added link to faq page
* [x ] Have you successfully ran tests with your changes locally?

doc(fse): added link to faq

---

_platforms/en/spid.md
_platforms/it/spid.md

Added [passport-spid](https://github.com/random42/passport-spid) to SPID libraries list.

docs: passport-spid library

---

_data/faq.yml
_data/l10n.yml
en/reuse/publication.md
it/riuso/pubblicazione.md

developers-italia-backend was renamed to publiccode-crawler.

chore(content): change links to developers-italia-backend

---

_platforms/en/anpr.md
_platforms/it/anpr.md

This PR removes an old link to the ANPR test platform.

Remove old ANPR test link

---

_platforms/it/fse.md

_platform/it/fse.md wrong </span> in html output introduced in: https://github.com/italia/developers.italia.it/pull/1316

fix(fse): wrong </span> in html output

---

_posts/it/2022-12-21-Developers-Italia-approda-su-Mastodon.md

Topic tags have to be downcase for them to work
Fix #1343

fix: topic tags in 2022-12-21 news

---

_platforms/en/spid.md
_platforms/it/spid.md

Added the Nimbus SDK for SPID OIDC

feat: added Nimbus for SPID OIDC SDKs

---

_platforms/en/spid.md
_platforms/it/spid.md

Explanatory text for Nimbus Java SDK

fix: [spid] nimbus text

---

_posts/it/2023-01-16-Angular-Roma-MeetUp-per-evolvere-Design-Kit.md

Inserito link a diretta streaming evento

---

_platforms/it/fse.md

doc: aggiornato testo fse

---

_platforms/it/fse.md

Update fse.md title and some cert requests

content: update fse

---

_data/l10n.yml

Fixing two broken URLs in the Vitality Index tooltip. 
Even if that's not the most user friendly page to point to 😄

fix: broken URLs for vitality-ranges.yml

---

_platforms/it/fse.md

Aggiunto link a doc transitorio

content: fse aggiunto link a transitorio in 

---

_posts/it/2023-02-17-metadati-come-standard-di-qualita.md

content: minor fixes to 2023-02-17 news

---

_posts/it/2023-02-17-metadati-come-standard-di-qualita.md

Added link to https://frictionlessdata.io/blog/2023/02/06/community-call/

Add link to community call blog news on frictionless

---

_posts/it/2023-02-17-metadati-come-standard-di-qualita.md

The URL should point to the start of the video

content: fix Youtube link in 2023-02-17 news

---

docker-compose.yml

* disable elastic search container disk threshold check
* [x ] Have you successfully ran tests with your changes locally?

chore(container): disable es disk threshold

---

Makefile

* https://github.com/italia/developers.italia.it/issues/1263
Fix for Makefile
Fixes https://github.com/italia/developers.italia.it/issues/1263

fix(makefile): fix bundle config path

---

en/reuse/publication.md
it/riuso/pubblicazione.md

publishers.thirdparty.yml is now in this repo
(https://github.com/italia/publiccode-crawler/issues/298#issuecomment-1429467772)

content: update link to publishers.thirdparty.yml

---

_platforms/it/fse.md

fse: nota per processo verifica servizio pubblicazione
* [x ] Have you successfully ran tests with your changes locally?

doc(fse): nota per verifica pubblicazione

---

_platforms/it/fse.md

change link description
* [ x] Have you successfully ran tests with your changes locally?

chore(fse): change link description

---

_data/publishers.thirdparty.yml

* Added `inPA (iOS)` to `publishers.thirdparty.yml`

Add `inPA (iOS)` to `publishers.thirdparty.yml`

---

_platforms/it/fse.md

fse: Update links to xsd and sch

chore(fse): update xsd sch links

---

_platforms/it/fse.md

fix(fse): broken link to agid

---

_platforms/en/designers.md

* Updated copy to match the status at Q4-23, where all the active kit has been brought under the design system umbrella
* Fixing broken/obsolete links 
Fixes #

Update copy: designers.md

---

_data/publishers.thirdparty.yml

* Nuovo plugin WordPress/ WooCommerce che aggiunge ai gateway di pagamento Carta della Cultura Giovani e Carta del Merito.
* [ x] I followed the indications in [CONTRIBUTING.md](https://github.com/italia/developers.italia.it/blob/main/CONTRIBUTING.md)
* [ x] The documentation related to the proposed change has been updated accordingly (also comments in code).
* [ x] Have you written new tests for your core changes, as applicable?
* [ x] Have you successfully ran tests with your changes locally?
Fixes #

WordPress/ WooCommerce plugin WC Carte Cultura

---

_data/publishers.thirdparty.yml

Add Interfacer among third parties

Add Interfacer

---

_data/people.yml

Thanks @ioggstream and Michela

content: update team status in contacts page

---

_layouts/software-details.html
_layouts/software.html

Temporarly remove the vitality, in preparation of #1405, as the the vitality data is not loaded into the API yet.

remove: temporarly remove vitality

---

.well-known/matrix/client
.well-known/matrix/server

Add Matrix federation well-known files for experimental Matrix server.

chore: add Matrix well-known files

---

_layouts/software-details.html
assets/js/App.js
assets/js/components/PubliccodeBadge.js
assets/js/components/Spinner.css
assets/js/components/Spinner.js

Add a status badge to every software page, displaying if the publiccode.yml was crawled
correctly.

feat: add publiccode.yml crawl status to software pages

---

_data/people.yml

chore: update team status in contacts page

---

package-lock.json
package.json

chore: dompurify update

---

assets/js/components/Catalogue/CatalogueFilters.js
assets/js/components/Catalogue/CatalogueHeader.js

Fix: url search catalogue parameters
